name: country
description: Generated country class with country_generator using countries.
version: 0.0.3
homepage: https://github.com/aaassseee/country
repository: https://github.com/aaassseee/country/tree/master/country
issue_tracker: https://github.com/aaassseee/country/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
#  country_generator:
#    path:
#      ../country_generator
  country_generator: ^0.0.3
  flutter_lints: ^1.0.4

country_generator:
  sourceFolder: submodule/countries
  outputFolder: lib/src